spring.application.name=videolibrary

spring.data.mongodb.auto-index-creation=true

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=video-library
spring.mongodb.username=admin
spring.mongodb.password=admin123
spring.mongodb.authentication-database=admin

jwt.secret=TsS0q4X1oHIirlIF1Nh2B50vgjwyJjPrnXeEGLCqXZx
jwt.expiration=3600000
