spring.application.name=videolibrary

spring.data.mongodb.auto-index-creation=true

spring.mongodb.host=${MONGO_HOST:mongo}
spring.mongodb.port=${MONGO_PORT:27017}
spring.mongodb.database=${MONGO_DATABASE:video-library}
spring.mongodb.username=${MONGO_USERNAME}
spring.mongodb.password=${MONGO_PASSWORD}
spring.mongodb.authentication-database=admin

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}

frontend.url=${FRONTEND_URL}